spring:
  application:
    name: account-app
  profiles:
    active: local
  eureka:
    client:
      service-url:
        defaultZone:
          http://localhost:8761/eureka/
info:
  build:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    name: @project.name@
    version: @project.version@