spring:
  application:
    name: profile-app
  profiles:
    active: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
info:
  build:
    artifactId: @project.artifactId@
    version: @project.version@
